### ISSUE TITLE
b64_sha256(data: str) Syntax error

### ISSUE THREAD

**Issue by evertide** [dpollardcouk/Huawei_E5186_API#1]
Hi,

I am getting a syntaxt error at b64_sha256(data: str) at the “:” location.

Anything I am doing wrong ?.  I am trying to get a E8372 to send and read sms.

Regards
Evert

**Comment by evertide** [comment]
Hi,
Found it defaulted to python2 and the argument is 3.6. Not Python 3.5 due to the isoformat having to arguments

**Comment by dpollardcouk** [comment]
Happy that this repo is being used and note that you've self fixed.
